<?php

namespace frontend\models;

use common\models\User;
use Yii;

/**
 * This is the model class for table "cook".
 *
 * @property int $id
 * @property int $idtruyen
 * @property int $userid
 * @property string $recaudio
 * @property string|null $rectile
 * @property string|null $startspeed
 * @property int|null $startime
 * @property int|null $timetao
 *
 * @property Audioo $idtruyen0
 * @property User $user
 */
class Cook extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public $infor;
    public static function tableName()
    {
        return 'cook';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['idtruyen', 'userid', 'recaudio'], 'required'],
            [['idtruyen', 'userid', 'startime', 'timetao'], 'integer'],
            [['recaudio', 'rectile', 'startspeed'], 'string', 'max' => 255],
            [['userid'], 'exist', 'skipOnError' => true, 'targetClass' => User::class, 'targetAttribute' => ['userid' => 'id']],
            [['idtruyen'], 'exist', 'skipOnError' => true, 'targetClass' => Audioo::class, 'targetAttribute' => ['idtruyen' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'idtruyen' => 'Idtruyen',
            'userid' => 'Userid',
            'recaudio' => 'Recaudio',
            'rectile' => 'Rectile',
            'startspeed' => 'Startspeed',
            'startime' => 'Startime',
            'timetao' => 'Timetao',
        ];
    }

    /**
     * Gets query for [[Idtruyen0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getIdtruyen0()
    {
        return $this->hasOne(Audioo::class, ['id' => 'idtruyen']);
    }
    public function save($runValidation = true, $attributeNames = null)
    {
        $idtruyen = $this->infor['id'];
        $startt = $this->infor['startt'];
        $starts = $this->infor['starts'];
        $recenta = $this->infor['recenta'];
        $recentat = $this->infor['recentat'];
        if ($this->isNewRecord) {
            $this->userid = Yii::$app->user->identity->id;
            $this->idtruyen = intval($idtruyen);
        }
        $this->recaudio = $recenta;
        $this->rectile = $recentat;
        $this->startime = intval($startt);
        $this->startspeed = $starts;
        $this->timetao = intval(1);

        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::class, ['id' => 'userid']);
    }
}
